config/routes.rb
Rails.application.routes.draw do
  root 'page#landing'

  get 'project/index'
  get 'project/download'

  get 'page/landing'
  get 'page/download'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def landing
		render :layout => false;
	end


	def download
		send_data '/assets/data/DrewGonzalesResume.pdf',
		:filename => "DrewGonzalesResume.pdf",
		:type => "application/pdf"
	end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
	def index
	end

	def download
		send_data '/assets/data/jawa.zip',
		:filename => "jawa.zip",
		:type => "application/zip"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<header>

	<title>Drew Gonzales</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag "application", params[:controller], :media => "all",'data-turbolinks-track'=>true %>
	<%= javascript_include_tag "application", params[:controller],'data-turbolinks-track'=>true %>
  	<!-- Compiled and minified CSS -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

  	<!-- Compiled and minified JavaScript -->
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
          

	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

	<meta charset="UTF-8">

</header>
<main>
	<nav>
		<div class="nav-wrapper teal">
			<%= link_to 'Home', root_path, class: "brand-logo"%>
			<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
			<ul class="right hide-on-med-and-down">
				<li><%= link_to 'Projects', project_index_path%></li>
			</ul>

			<ul class="side-nav" id="mobile-demo">
				<li><%= link_to 'Projects', project_index_path%></li>
			</ul>
		</div>
	</nav>
	<%= yield %>
</main>
<footer class="page-footer teal">
	<div class="container">
		<div class="row">
			<div class="col l6 s12">
				<h5 class="white-text">Drew Gonzales</h5>
				<p class="grey-text text-lighten-4">If you've found any errors on the page, contact me!</p>
			</div>
			<div class="col l4 offset-l2 s12">
				<h5 class="white-text">Site Map</h5>
				<ul>
					<li><%= link_to 'Home', root_path, class: "grey-text text-lighten-3"%></li>
					<li><%= link_to 'Projects', project_index_path, class: "grey-text text-lighten-3"%></li>
					<li><%= mail_to 'drew.gonzales@ucla.edu', "Contact", class: "grey-text text-lighten-3"%></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="footer-copyright">
		<div class="container">
			Created with swag using Materialize CSS. 2016. 
		</div>
	</div>
</footer>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>

app/views/page/landing.html.erb
<!DOCTYPE html>
<html>
	<header class="mdl-layout__header">

		<title>Drew Gonzales</title>
		<%= csrf_meta_tags %>
	<%= stylesheet_link_tag "application", params[:controller], :media => "all",'data-turbolinks-track'=>true %>
	<%= javascript_include_tag "application", params[:controller],'data-turbolinks-track'=>true %>

		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

		<meta charset="UTF-8">


	</header>

	<body>
		<div class="container">
			<div class="spacer">
				<div class="jumbotron"></div>
				<div class="row">
					<div class="col s12 l6 push-l6">
						<div class="card blue-grey darken-1">
							<div class="card-content white-text">
								<span class="card-title">Hi. I'm Drew.</span><br>
								<p>I hope to revolutionize the modern home with artificial intelligence.</p><br>
								<p>Click the cards to learn about me.</p>
							</div>
							<div class="card-action">
								<%= link_to 'Projects', project_index_path%>
								<%= link_to 'LinkedIn', "https://www.linkedin.com/in/drew-gonzales-07551b92"%>
								<%= link_to 'GitHub', "https://www.github.com/kdrewgonzales"%>
								<a href="https://www.dropbox.com/s/wa61ar0n0dxb04j/DrewGonzalesResume.pdf?dl=0">Resume</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="col s12 m12 l6">
					<div class="card small z-depth-3">
						<div class="card-image waves-effect waves-block waves-light">
							<%= image_tag 'code.jpg', class: "activator"%>
						</div>
						<div class="card-content">
							<span class="card-title activator grey-text text-darken-4">Projects<i class="material-icons right">more_vert</i></span>
							<p><%= link_to 'Projects', project_index_path%></p>
						</div>
						<div class="card-reveal">
							<span class="card-title grey-text text-darken-4">Projects<i class="material-icons right">close</i></span>
							<p>My interests in the computing field are in web design and artificial intelligence.</p>
							<p>The projects I'm most excited about are the ones done in the Electron framework. Check 'em out!</p>
						</div>
					</div>

					<div class="card large z-depth-3">
						<div class="card-image waves-effect waves-block waves-light">
							<%= image_tag 'band.jpg', class: "activator"%>
						</div>
						<div class="card-content">
							<span class="card-title activator grey-text text-darken-4">Education<i class="material-icons right">more_vert</i></span>
							<p><a href="https://www.ucla.edu">University of California, Los Angeles</a></p><br>
							<p>Mathematics of Computation, B.S.</p>
							<p>Class of 2017</p>
						</div>
						<div class="card-reveal">
							<span class="card-title grey-text text-darken-4">Education<i class="material-icons right">close</i></span>
							<p>I'm currently and undergraduate studying Mathematics of Computation. Aside from my studies,
							I'm involved with the UCLA Solid Gold Sound Marching band, and the UCLA Club Cycling team.
							I'm also a Regents Scholar at UCLA</p>
							<ul >
								<li>CS 32     - Data Structures & Algorithms</li>
								<li>CS 33			- Computer Organization</li>
								<li>CS 35L    - Software Construction Laboratory</li>
								<li>CS 111  	- Operating System</li>
								<li>CS 161    - Artificial Intelligence</li>
								<li>CS 180    - Algorithms and Complexities</li>
								<li>Math 115A - Linear Algebra</li>
								<li>Math 142  - Mathematical Modeling</li>
								<li>Math 164  - Optimization</li>
								<li>Math 167  - Game Theory</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col s12 m12 l6">
					<div class="card z-depth-3">
						<div class="card-image waves-effect waves-block waves-light">
							<%= image_tag 'bikes.jpg', class: "activator"%>
						</div>
						<div class="card-content">
							<span class="card-title activator grey-text text-darken-4">Cycling<i class="material-icons right">more_vert</i></span>
							<p><a href="https://www.usacycling.org/results/?compid=303655">Results</a></p>
						</div>
						<div class="card-reveal">
							<span class="card-title grey-text text-darken-4">Cycling<i class="material-icons right">close</i></span>
							<p>I've been a competitive cyclist since I was 15 years old. I have experience racing at the
							national level. My favorite races were Valley of the Sun, Cascade, and Junior National Cycling
							Championships.</p> <br>
							<p>I'm currently a member of the UCLA Club Cycling Team and the webmaster. Check us out on
							<a href="https://www.facebook.com/groups/cycling.ucla/">Facebook</a>!</p>
						</div>
					</div>

					<div class="card blue-grey darken-1">
						<div class="card-content white-text">
							<span class="card-title">Contact</span><br>
							<p>drew.gonzales@ucla.edu</p><br>
						</div>
						<div class="card-action">
							<!-- <%= link_to 'Resume', page_download_path%> -->
							<a href="https://www.dropbox.com/s/wa61ar0n0dxb04j/DrewGonzalesResume.pdf?dl=0">Resume</a>
							<a href="https://github.com/kdrewgonzales">GitHub</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
	<footer class="page-footer teal">
		<div class="container">
			<div class="row">
				<div class="col l6 s12">
					<h5 class="white-text">Drew Gonzales</h5>
					<p class="grey-text text-lighten-4">If you've found any errors on the page, contact me!</p>
				</div>
				<div class="col l4 offset-l2 s12">
					<h5 class="white-text">Site Map</h5>
					<ul>
						<li><%= link_to 'Home', root_path, class: "grey-text text-lighten-3"%></li>
						<li><%= link_to 'Projects', project_index_path, class: "grey-text text-lighten-3"%></li>
						<li><%= mail_to 'drew.gonzales@ucla.edu', "Contact", class: "grey-text text-lighten-3"%></li>

					</ul>
				</div>
			</div>
		</div>
		<div class="footer-copyright">
			<div class="container">
				Created with swag using Materialize CSS. 2016.
			</div>
		</div>
	</footer>
</html>

app/views/project/index.html.erb
<body>
	<div class="container">
		<div class="row">
			<div class="col s12 m6 l6">
				<div class="card">
					<div class="card-image waves-effect waves-block waves-light">
					<%= image_tag 'material-shot.jpg', class: "activator"%>
					</div>
					<div class="card-content">
						<span class="card-title activator grey-text text-darken-4">Material Shot Trainer<i class="material-icons right">more_vert</i></span>
						<p><a href="https://github.com/kdrewgonzales/material-shot">Project Repository</a></p>
						<p><a href="https://www.dropbox.com/s/x3jcsmyzeiwdr1l/MaterialShot-linux-x64.zip?dl=0">Linux Executable</a></p>
					</div>
					<div class="card-reveal">
						<span class="card-title grey-text text-darken-4">Material Shot Trainer<i class="material-icons right">close</i></span>
						<p>This is a small game that will help users strengthn their accuracy and speed with a mouse. These
						excercises are supposed to help with first person shooters and improve shot accuracy and reflex time. Here
						is a link to the game for <a href="https://www.dropbox.com/s/x3jcsmyzeiwdr1l/MaterialShot-linux-x64.zip?dl=0">linux</a>.
						Just navigate through the folder and run the "MaterialShot" script.</p>
					</div>
				</div>
				<div class="card">
					<div class="card-image waves-effect waves-block waves-light">
						<%= image_tag 'mollys-adventure.jpg', class: "activator"%>
					</div>
					<div class="card-content">
						<span class="card-title activator grey-text text-darken-4">Molly's Adventure<i class="material-icons right">more_vert</i></span>
						<p><a href="https://github.com/kdrewgonzales/mollys-adventure">Project Repository</a></p>
					</div>
					<div class="card-reveal">
						<span class="card-title grey-text text-darken-4">Molly's Adventure<i class="material-icons right">close</i></span>
						<p>This is a small 2d game where a user will use the space bar to jump
						from platform to platform, while using the mouse to shoot the red
						floating enemies in the sky. This game is written using Githubs Electron
						for desktop applications. </p>
					</div>
				</div>
			</div>
			<div class="col s12 m6 l6">
				<div class="card small">
					<div class="card-image waves-effect waves-block waves-light">
						<%= image_tag 'jawa.jpg', class: "activator"%>
					</div>
					<div class="card-content">
						<span class="card-title activator grey-text text-darken-4">Project Jawa<i class="material-icons right">more_vert</i></span>
						<p><a href="https://www.dropbox.com/s/smezf7k8ckwlv5u/Jawa.zip?dl=0">Project File</a></p>
					</div>
					<div class="card-reveal">
						<span class="card-title grey-text text-darken-4">Project Jawa<i class="material-icons right">close</i></span>
						<p>This was my favorite project from my computer science class at UCLA. The project was to create a "changefile"
						for a text file. In the problem given, a user has a text file. Then I need to push a "changefile" to the user to
						update his file. The objective was to create the smallest changefile possible by copying the parts of the file
						that the user already has, and only telling the user what sections of text need to be added.</p>
					</div>
				</div>
				<div class="card">
					<div class="card-image waves-effect waves-block waves-light">
						<%= image_tag 'ucon.jpg', class: "activator"%>
					</div>
					<div class="card-content">
						<span class="card-title activator grey-text text-darken-4">UConfessions<i class="material-icons right">more_vert</i></span>
						<p><a href="https://github.com/kdrewgonzales/UConfessions">Project Repository</a></p>
					</div>
					<div class="card-reveal">
						<span class="card-title grey-text text-darken-4">UConfessions<i class="material-icons right">close</i></span>
						<p>This is the first project I wrote, and the first time I learned a programming language. UConfessions just allows
							users to post a story. Then users at other UCs can view it on the app. Unfortunately, I used Parse.com to host the
							data, but Parse went out of business. The data will soon be unavailable.</p>
					</div>
				</div>
				<div class="card">
					<div class="card-image waves-effect waves-block waves-light">
						<%= image_tag 'pokething.jpg', class: "activator"%>
					</div>
					<div class="card-content">
						<span class="card-title activator grey-text text-darken-4">Poke Thing<i class="material-icons right">more_vert</i></span>
						<p><a href="https://github.com/kdrewgonzales/pokething">Project Repository</a></p>
					</div>
					<div class="card-reveal">
						<span class="card-title grey-text text-darken-4">Poke Thing<i class="material-icons right">close</i></span>
						<p>This framework currently allows another programmer to begin constructing a tile game of their own.
						Eventually, I play to write a full length game, but the only functionality that it currently has is
						creating maps and traveling between them. There are npcs that roam the map. You can talk to them
						by pressing k, and wander the map using wasd.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>